pipeline {
    agent {
        docker {
            image 'gradle:6.6.1-jre14-openj9'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                sh 'git clone https://github.com/alezanshe/jenkins.git'
            }
        }
        stage('Compile') {
            steps {
                sh '''
                cd jenkins/calculator
                ./gradlew compileJava
                '''
            }
        }
        stage('Unit Tests') {
            steps {
                sh '''
                cd jenkins/calculator
                ./gradlew test
                '''
            }
        }
    }
}