name: CI

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: hangman-front/package-lock.json
      - name: Install Dependencies
        working-directory: ./hangman-front
        run: npm ci
      - name: Build
        working-directory: ./hangman-front
        run: npm run build
      - name: Run Tests
        working-directory: ./hangman-front
        run: npm run test
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-code
          path: hangman-front/dist/

  docker-login-build-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: hangman-front/package-lock.json
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-code
          path: hangman-front/dist/
      - name: Docker Login
        run: echo ${{ secrets.TOKEN }} | docker login ghcr.io -u echo ${{ secrets.GITHUB_ACTOR }} --password-stdin
      - name: Docker Build
        working-directory: ./hangman-front
        run: docker build -t ghcr.io/alezanshe/hangman-front/hangman-front:latest .
      - name: Docker push
        run: docker push ghcr.io/alezanshe/hangman-front/hangman-front:latest