pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                sh '''
                git clone https://github.com/alezanshe/jenkins.git
                cd jenkins1/
                '''
            }
        }
        stage('Compile') {
            steps {
                sh './gradlew compileJava'
            }
        }
        stage('Unit Tests') {
            steps {
                sh './gradlew test'
            }
        }
    }
}