apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-cm
  labels:
    app: demo-app-cm
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "demo-db-svc"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_PORT: "5432"
  DB_NAME: "todos_db"
  DB_VERSION: "10.4"