apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-db-pv
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv01
  accessModes:
    - ReadWriteOnce
  storageClassName: demo-db-sc