apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
spec:
  selector:
    matchLabels:
      app: demo-app-svc
  template:
    metadata:
      labels:
        app: demo-app-svc
    spec:
      containers:
      - name: demo-app
        image: alezanshe/todo-app-monolith-app
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: demo-app-cm
                key: NODE_ENV
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: demo-app-cm
                key: PORT
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: demo-app-cm
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: demo-app-cm
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: demo-app-cm
                key: DB_PASSWORD
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: demo-app-cm
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: demo-app-cm
                key: DB_NAME
          - name: DB_VERSION
            valueFrom:
              configMapKeyRef:
                name: demo-app-cm
                key: DB_VERSION
        ports:
        - containerPort: 3000